docker/libkv

.travis.yml, script/.validate, script/coverage, script/travis_consul.sh, script/travis_etcd.sh, script/travis_zk.sh, script/validate-gofmt
=> Include travis.yml and store install scripts

README.md
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>
=> README: Add godoc/travis/coveralls badges.

store/consul/consul_test.go, store/etcd/etcd_test.go, store/zookeeper/zookeeper_test.go, testutils/utils.go
We don't want to import the testing library when you import "github.com/docker/libkv/store".
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Remove the test helpers from the main package.

libkv.go, libkv_test.go, store/consul/consul.go, store/consul/consul_test.go, store/etcd/etcd.go, store/etcd/etcd_test.go, store/mock/mock.go, store/store.go, store/zookeeper/zookeeper.go, store/zookeeper/zookeeper_test.go
=> Remove dependency to testify through the mock package

.travis.yml
=> Update go get urls in travis for go vet and go cover

store/store.go
Follow up to https://github.com/docker/swarm/pull/954
Signed-off-by: Ahmet Alp Balkan
=> Use Backend type for stores

store/etcd/etcd.go
`etcd` Watch returns nil when we stop the store so client may panic in result. We just check for nil values inside the watch and stop if this happens.
related to docker/swarm#980
=> Enforce nil check for result in etcd Watch

store/zookeeper/zookeeper.go
related to docker/swarm#974
ping @aluzzardi, @vieux
=> fix zookeeper List which occasionally misses entries

store/etcd/etcd.go, testutils/utils.go
=> fix etcd lock, change ttl Update in Lock to use CompareAndSwap

store/etcd/etcd.go
Signed-off-by: Robert Springer <springi99@gmail.com>
=> fixing issue #26, error 100

store/consul/consul.go
Related to docker/swarm#1091
ping @vieux @aluzzardi  @ahmetalpbalkan 
=> return error when specifying multiple IPs with Consul

README.md
ping @aluzzardi @vieux @mavenugo 
=> Add warning to doc for known etcd and overall API consistency issues

store/zookeeper/zookeeper.go, testutils/utils.go
=> Fix zookeeper not exist key error

store/consul/consul.go, store/etcd/etcd.go, store/store.go, store/zookeeper/zookeeper.go, testutils/utils.go
Sorry, I missed this in the last PR.
This one also contains some minor fix for docs and adds tests for Exist function.
=> Fix zookeeper List function not exist key error

libkv.go, libkv_test.go, store/boltdb/boltdb.go, store/boltdb/boltdb_test.go, store/consul/consul_test.go, store/etcd/etcd_test.go, store/store.go, store/zookeeper/zookeeper_test.go, testutils/utils.go
Signed-off-by: Santhosh Manohar <santhosh@docker.com>
=> BoltDB backend support for libkv

store/boltdb/boltdb.go, store/boltdb/boltdb_test.go
=> Create dir first before opening data file of boltdb

store/boltdb/boltdb.go, store/boltdb/boltdb_test.go
fixes #54 
Signed-off-by: Madhu Venugopal <madhu@docker.com>
=> Honoring ConnectionTimeout in boltdb

README.md, store/etcd/etcd.go, store/store.go
Carry #45 
Adds etcd tls client auth
=> Carry #45: Add etcd TLS client code and update README.md.

.travis.yml, script/travis_etcd.sh
=> Update etcd version in travis

libkv.go, store/boltdb/boltdb.go, store/store.go
=> Change unsupported call error in boltdb backend to use general store error

store/boltdb/boltdb.go, store/boltdb/boltdb_test.go, store/store.go
This allows multiple connections to Bolt BD from an app.
Signed-off-by: Santhosh Manohar <santhosh@docker.com>
=> Add transient connection option to bolt db

store/boltdb/boltdb.go
Currently boltdb uses a handle which can be accessed
concurrently from multiple go routines and all of them
trying to open and close the boldb db handle which can
cause havoc. Use a mutex to serialize db access and
handle access.
Signed-off-by: Jana Radhakrishnan <mrjana@docker.com>
=> Synchronize boltbd libkv apis

store/zookeeper/zookeeper.go, testutils/utils.go
=> Fix zookeeper atomic put suffix key

store/boltdb/boltdb.go
Currently boltdb uses a handle which can be accessed
concurrently from multiple go routines and all of them
trying to open and close the boldb db handle which can
cause havoc. Use a mutex to serialize db access and
handle access.
Signed-off-by: Jana Radhakrishnan <mrjana@docker.com>
=> Cherry-pick 9ed4ad32b79b696b94fbfa11bb1533c6ba2f4255 into master (Synchronize boltbd libkv apis)

.travis.yml, script/travis_zk.sh
=> Fix zookeeper CI download link, upgrade to zk 3.5.1 alpha

.travis.yml, script/travis_consul.sh
=> Update consul version in CI to 0.6.0

LICENSE.code, README.md
Signed-off-by: William Lee <william_leez@foxmail.com>
Update Copyright date.
=> Update Copyright date.

README.md
=> Update link and references to the new docker leadership repository

.travis.yml, script/travis_zk.sh
=> ci: update go version in travis

.travis.yml
=> tests: remove go get vet from travis yml

.travis.yml
=> travis: update etcd to v3.0.0

store/zookeeper/zookeeper.go
=> zk: fix wrong error code check on List

.github/workflows/dummy.yml
Follow-up https://github.com/docker/libkv/pull/220#issuecomment-996778706
Merge this PR to enable GitHub Actions on this repo and then workflow of #220 will be turned on
cc @thaJeztah @errordeveloper 
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> Dummy workflow to enable GitHub Actions
