- libkv.go
- store/consul/consul.go
- store/zookeeper/zookeeper.go
Feel free to close this if you don't agree but I don't like logging in libraries, better to log upstream when using them and have more control over what's logged :)
Signed-off-by: Antonio Murdaca <runcom@linux.com>
> Remove logging in library

- script/travis_consul.sh
- store/consul/consul.go
- testutils/utils.go
From the Consul PR to add TTLs:
> Consul will take the conservative approach of internally multiplying the TTL by 2x
This PR fixes that by dividing the `ttl` by 2 (which brings the ttl behavior on par with `etcd`). There is no check so if the `ttl` provided is `< 20s` the create session will fail if Consul is not properly configured to handle lower `ttl` bounds.
The choices are:
- do the proper check but we'll need an additional parameter to override the default check and accept lower values (for testing as we have a `1s` custom lower bound `ttl` value)
- keep it as it is and assume that people using the lib will provide a reasonable `ttl` according to their setup :grin:/
> Fix conservative TTL multiplier in Consul and unnecessary lock at each Put operation

- store/consul/consul.go
- store/etcd/etcd.go
- store/store.go
- store/zookeeper/zookeeper.go
- testutils/utils.go
We need a way to put a new key, value pair into the datastore, ensuring it doesn't overwrite anything existing.
Libkv only defines an `AtomicPut` operation for setting a key in a way that ensures we don't trample another write.
However, in `etcd` the consistent operations of "update" and "create" are distinct (`CompareAndSwap` and `Create` in the go API).
In this PR, we modify `AtomicPut` to interpret LastIndex == 0 (e.g. newly initialized) as a `Create`.  This allows the user to put a new key, ensuring that it is not overwriting another write.
I'm speculating on the API here, since it isn't directly documented what the expectation is for `AtomicPut`.  Another way to accomplish this requirement is to define a separate call `AtomicCreate` which takes no `previous` value.  Can one of the …
> Support "Atomic Create" in etcd

- store/etcd/etcd.go
Calls to `Get` and `List` in `Watch` and `WatchTree` are misplaced for `etcd` which causes the watch to not work properly with `libnetwork` and `swarm` for the Leader Election recovery on `etcd`
See #26 
> Correct misplaced calls to Get/List in Watch/WatchTree for etcd

- libkv.go
- libkv_test.go
- store/store.go
When I tried to start docker with `docker -d  --bip 192.168.1.0/16 -D -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --kv-store=Zookeeper:127.0.0.1:2181`, I got the error "Backend storage not supported yet, please choose another one". There isn't any docs in docker/libnetwork/libkv telling it's `zk` instead of `Zookeeper`. So I think it's better to make the error message self-explaining.
> Notify user of supported backend storage

- store/consul/consul.go
- store/consul/consul_test.go
- store/etcd/etcd.go
- store/etcd/etcd_test.go
- store/store.go
- store/zookeeper/zookeeper.go
- store/zookeeper/zookeeper_test.go
- testutils/utils.go
Drops the `Ephemeral`/`Heartbeat` config field combination to use a single `TTL` field. Most of the stores are using `TTL`'s, so this is better overall.
fixes #23
replaces #24
> Change Heartbeat/Ephemeral combination to use a single TTL field

- store/consul/consul.go
- store/consul/consul_test.go
- store/etcd/etcd.go
- store/etcd/etcd_test.go
- store/zookeeper/zookeeper.go
- store/zookeeper/zookeeper_test.go
- testutils/utils.go
Keys with suffix backslash is not allowed for zookeeper.
```
chenchun@chenchun-T450:/usr/local/zookeeper-3.4.6$ bin/zkCli.sh
...
[zk: localhost:2181(CONNECTED) 0] ls /foo
[]
[zk: localhost:2181(CONNECTED) 1] ls /foo/
Command failed: java.lang.IllegalArgumentException: Path must not end with / character
[zk: localhost:2181(CONNECTED) 2] create /foo1/ ""
Command failed: java.lang.IllegalArgumentException: Path must not end with / character
[zk: localhost:2181(CONNECTED) 3] create /foo1 "" 
Created /foo1
[zk: localhost:2181(CONNECTED) 4] create //foo2 "" 
Command failed: java.lang.IllegalArgumentException: Invalid path string "//foo2" caused by empty node name specified @1
```
> Fix ZooKeeper backend suffix backslash key

- README.md
- libkv.go
- libkv_test.go
- store/boltdb/boltdb.go
- store/boltdb/boltdb_test.go
- store/consul/consul.go
- store/consul/consul_test.go
- store/etcd/etcd.go
- store/etcd/etcd_test.go
- store/zookeeper/zookeeper.go
- store/zookeeper/zookeeper_test.go
fixes #49 
@mavenugo Is that what you had in mind? I managed to update libkv Godeps in swarm without boltDB thanks to this (see the `README`). If you have a better approach let me know :smile: 
> Refactor libkv to not directly import storage backends

- store/boltdb/boltdb.go
Found this bug during running unit tests of libnetwork.
> Fix AtomicPut panic if previous KVPair is not nil and key not exists in boltdb

- store/consul/consul.go
- store/consul/consul_test.go
- store/etcd/etcd.go
- store/etcd/etcd_test.go
- store/mock/mock.go
- store/store.go
- store/zookeeper/zookeeper.go
- store/zookeeper/zookeeper_test.go
- testutils/utils.go
Related to docker/swarm#930 and docker/swarm#1227
Add TTL on `Lock` for Consul and add tests for `etcd`, `consul` and `zookeeper`.
Also includes a `stopChan` for Consul and etcd in order to perform the test on the Lock `TTL`.
> Add TTL to Consul lock using store.LockOptions

- store/etcd/etcd.go
Not aligned with other backends (Consul client handles the stop chan directly and zookeeper does not take any stop chan), but kind of feels horrible to return `nil, nil` in this one...
> Return a useful error for etcd Lock when aborting the Lock operation instead of nil, nil

- README.md
> Add section for supported backend versions in README

- store/zookeeper/zookeeper.go
#41 rightfully removed the portion checking for the `SOH` character but the issue is still there, even if rare  and hardly reproducible it occasionally breaks swarm Integration Tests with:
`ERRO[0134] Discovery error: missing port in address  `
/cc @chenchun @vieux 
> Fix zookeeper regression with missing values

- store/consul/consul.go
Hi, I think there is a misspelling in your comment.
How about this?
"timout" to "timeout"
> Fix typo in comment

- store/etcd/etcd.go
Etcd TTLs are in seconds, without this fix the
ticker goes off uncontrollably every millisecond,
flooding etcd with put requests
Signed-off-by: Mariusz Borsa <mborsa@polyverse.io>
> Fix incorrect Etcd lock ticker initialization

- store/etcd/etcd.go
- store/store.go
- testutils/utils.go
Migrates the `etcd` driver codebase from `coreos/go-etcd` (deprecated) to `coreos/etcd/client`.
Amongst the notable changes you can now specify an `IsDir` parameter to `WriteOptions` which allows to circumvent the directory/key distinction on creating a key with `Put` and watching that key with `Watch`.
Until `etcd` APIv3 is finalized, a conservative measure is to pass `isDir:true` to `Put` before calling `Watch` on that key so that it is considered as a directory for `etcd`. Consul and zookeeper are ignoring this parameter.
(Tests have been slightly changed notably for `AtomicPut` because `0` is interpreted as `ignore` with the new client)
This needs to be tested against `swarm` and `libnetwork` first.
Fixes: #53 
Related to docker/libnetwork#577
Signed-off-by: Alexandre Beslic …
> Migrate etcd driver from 'go-etcd' to `etcd/client`

- README.md
Fixes #50 
Drops the **"to end users"** from documentation license grant as this seems superfluous and confusing (and not following the Creative Commons official guidelines).
/cc @onlyjob @thaJeztah @moxiegirl does that sound good to you? Thanks.
> Drops 'to end users' from documentation license grant

- store/consul/consul.go
Add a simple retry mechanism for session renewal when using `TTLs` in case the version of Consul is < `0.5.0` or more generally does not support sessions to hold a TTL.
Before, if using an unsupported version of Consul, the session renew would hang not throwing any useful error to the user.
> Session renewal retry count for Consul versions not supporting Sessions

- store/zookeeper/zookeeper.go
- testutils/utils.go
Carrying to make sure we get this on time for the freeze.
replaces #82 
ping @mavenugo @chenchun
> Carry #82: Fix zookeeper atomic put suffix key

- store/boltdb/boltdb.go
- testutils/utils.go
Signed-off-by: Santhosh Manohar <santhosh@docker.com>
> boltDB AtomicDelete fails for non-existent key

- store/consul/consul.go
- store/etcd/etcd.go
- store/zookeeper/zookeeper.go
- testutils/utils.go
Align on #86 to throw `ErrKeyNotFound` on `AtomicDelete` for every backend
/cc @sanimej @mavenugo 
> Align ErrKeyNotFound error on AtomicDelete for all backends

- store/boltdb/boltdb.go
- store/consul/consul.go
- store/etcd/etcd.go
- store/store.go
- store/zookeeper/zookeeper.go
- testutils/utils.go
When using AtomicPut with 'previous' set at nil, it interprets
that the Key should be created with the AtomicPut. Instead of
returning a generic error, we return store.ErrKeyExists if the
key exists in the store during the operation.
> Return store.ErrKeyExists on AtomicPut

- store/consul/consul.go
@abronan while experimenting with libkv's lock functionality with consul backend, I observed `ErrLockConflict` error from https://github.com/hashicorp/consul/blob/06926f3b3556716c985c8df7a9ff77fa5096c719/api/lock.go#L195
It seems consul is expecting a magic value of `LockFlagValue` in the KVPair's Flag in order to allow locking the key.
This PR is just to discuss the issue and a quick hack that I added in libkv.
AFAIK swarm uses lock functionality for leader election. But it doesnt seem to be impacted by this in a consul backend. Can you share any info you might have on this ?
Signed-off-by: Madhu Venugopal <madhu@docker.com>
> Consul expects "magic" flag to support locking a kvpair

- store/store.go
The typo was found and fixed by codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix typo in error text

- store/etcd/etcd.go
- store/etcd/etcd_test.go
- store/store.go
fixes #119 
This is the most simple solution to add support for etcd authentication. As explained in #119, this feature was added in etcd version 2.1. @abronan was concerned about compatibility of this feature with future versions of the etcd API. I thought about this and came up with the plan to 
* suggest this minimalistic change 
* discuss here whether the credentials one can set on the `store.Config` should better be more abstract.
In both cases, the backends that support authentication would have to check whether the configured credential type is supported in their constructor.
By introducing a `Credentials` interface, one could make different types of credentials pluggable.
```go
// store/store.go
type Config struct {
...
Credentials Credentials
}
type Credentials interface{}
// …
```
> Add support for etcd authentication

- store/consul/consul.go
This PR changes the lock behavior for consul to not
renew a session for a lock after the contact with the
store was lost. This is required for leader election as
if the leader fails, the past locker would still renew
the session and not be notified of the change of role.
> consul: privilege liveness over safety for lock after store failure

- store/boltdb/boltdb.go
While doing a boltdb operation and if the bucket is not found
we should not return a boltdb specific bucket not found error
because this causes leaky abstraction where in the user of libkv
needs to know about boltdb and import boltdb dependencies
neither of which is desirable. Replaced all the bucket not found
errors with the more generic `store.ErrKeyNotFound` error which
is more appropriate.
Signed-off-by: Jana Radhakrishnan <mrjana@docker.com>
> Do not return boltdb bucket not found error

- .travis.yml
- store/boltdb/boltdb.go
- also in case of no persistent connection
- Also fixing CI by bumping go version in `.travis.yml`
Related to https://github.com/docker/docker/issues/26251
Related to https://github.com/docker/libnetwork/issues/1374
Supersedes #135 
Signed-off-by: Alessandro Boch aboch@docker.com
> Allow client to set boltdb timeout

- store/consul/consul_test.go
- store/etcd/etcd.go
- store/etcd/etcd_test.go
- store/zookeeper/zookeeper_test.go
- testutils/utils.go
1. Any connection errors on the first key Set attempt may
cause 2 clients to think they have acquired the lock if
the second set attempt succeeds.
2. The wait loop was not checking for 'compareAndDelete'
events which means that a client may never retry to set
the lock key.
> Fix etcd Lock bugs

- .travis.yml
- script/travis_zk.sh
- store/boltdb/boltdb.go
Signed-off-by: John Howard <jhoward@microsoft.com>
Part fix for https://github.com/docker/libnetwork/issues/1950
gitHub.com/boltdb/bolt is no longer being maintained. From https://github.com/boltdb/bolt:
> Unfortunately I no longer have the time or energy to continue this work. Bolt is in a stable state and has years of successful production use. As such, I feel that leaving it in its current state is the most prudent course of action.
>
> If you are interested in using a more featureful version of Bolt, I suggest that you look at the CoreOS fork called bbolt.
In order to fix the libnetwork issue, I need to change consumers over to the new package, so that I can ultimately pull in this fix: https://github.com/etcd-io/bbolt/pull/122.
This PR uses the import syntax recommended at …
> boltdb/bolt is not maintained. Use bbolt instead.

- store/zookeeper/zookeeper.go
The old one is dead, and has a dependency that has vanished off the face of the earth.
```
github.com/docker/docker/libnetwork imports
github.com/docker/libkv/store/zookeeper imports
github.com/samuel/go-zookeeper/zk tested by
github.com/samuel/go-zookeeper/zk.test imports
camlistore.org/pkg/throttle: module camlistore.org@latest found (v0.0.0-20171230002226-a5a65f0d8b22), but does not contain package camlistore.org/pkg/throttle
```
The code builds without further changes.
> Use new Zookeeper library
